- name: Execute command on Huawei switch
  hosts: huwaei
  gather_facts: no
  tasks:
    - name: Display version
      ansible.netmiko_send_command:
        command_string: display version
      register: result

    - name: Print result
      debug:
        var: result.stdout_lines
