- name: Install snmp huwaei
  hosts: huawei
  tasks:
  - name: Display clock
    ansible.netmiko_send_command:
      command_string: display clock
    register: result
  - name: Print result
    debug:
      var: result.stdout_lines
  